version: '3.8'

services:
  order_service:
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - order_network  
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=furqan
      - DATABASE_PASSWORD=furqan
      - DATABASE_NAME=Order

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: furqan
      POSTGRES_PASSWORD: furqan
      POSTGRES_DB: Order
    ports:
      - "5431:5432"
    networks:
      - order_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "furqan", "-d", "Order", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s


networks:
  order_network:
    driver: bridge