version: '3.8'

services:
  restaurant_service:
    build:
      context: .
    ports:
      - "8082:8082"
    networks:
      - restaurant_network  
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=furqan
      - DATABASE_PASSWORD=furqan
      - DATABASE_NAME=Restaurant

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: furqan
      POSTGRES_PASSWORD: furqan
      POSTGRES_DB: Restaurant
    ports:
      - "5430:5432"
    networks:
      - restaurant_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "furqan", "-d", "Restaurant", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s


networks:
  restaurant_network:
    driver: bridge