version: '3'
services:
  user_service:
    build:
      context: .
    ports:
      - "8083:8083"
    networks:
      - user_network  
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db  
      - DATABASE_PORT=5432
      - DATABASE_USER=furqan
      - DATABASE_PASSWORD=furqan
      - DATABASE_NAME=User
      

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: furqan
      POSTGRES_PASSWORD: furqan
      POSTGRES_DB: User
    ports:
      - "5430:5432"  
    networks:
      - user_network  
      
networks:
  user_network:
    driver: bridge