version: '3'
services:
  user_service:
    build:
      context: .
    ports:
      - "8083:8083"
    networks:
      - user_network  
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=furqan
      - DATABASE_PASSWORD=furqan
      - DATABASE_NAME=User
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: furqan
      POSTGRES_PASSWORD: furqan
      POSTGRES_DB: User
    ports:
      - "5432:5432"
    networks:
      - user_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "furqan", "-d", "User", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
      
networks:
  user_network:
    driver: bridge